language: node_js

node_js:
  - "12"

branches:
  only:
    - master
    - /v\d+.\d+(\.d+)?(-[a-zA-Z0-9]+)?/

before_install:
  # Install Mongo DB
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-4.0.2.tgz
  - tar -zxvf mongodb-linux-x86_64-4.0.2.tgz
  # Install mongo shell
  - wget https://downloads.mongodb.org/linux/mongodb-shell-linux-x86_64-debian81-4.0.9.tgz
  - tar -zxvf mongodb-shell-linux-x86_64-debian81-4.0.9.tgz

  # Make data directory and start DB
  - mkdir ${PWD}/mongodb-linux-x86_64-4.0.2/data
  - ${PWD}/mongodb-linux-x86_64-4.0.2/bin/mongod --replSet mmtb_replica --dbpath ${PWD}/mongodb-linux-x86_64-4.0.2/data --logpath ${PWD}/mongodb-linux-x86_64-4.0.2/mongodb.log --fork

before_script:
  - sleep 25
  - mongodb-linux-x86_64-debian81-4.0.9/bin/mongo --eval 'rs.initiate()'
  - sleep 5
  - mongodb-linux-x86_64-debian81-4.0.9/bin/mongo mmtb_test --eval 'db.createUser({user:"jsmrcaga", pwd:"test_password", roles:["readWrite"]});'

before_deploy:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

deploy:
  provider: script
  script: npm publish
  on:
    tags: true

git:
  depth: 2

