version: "3.1"
services:
  db:
    image: mongo:5
    container_name: executor-test
    ports:
      - "27777:27017"
    command: --replSet "mongoset" --bind_ip_all
    volumes:
      # to run commands for mongo startup
      - ./docker:/docker-entrypoint-initdb.d:ro

  app:
    build: .
    depends_on:
      - "db"
    environment:
      - NODE_ENV=development
    volumes:
      - /code/node_modules
      - .:/code
